# Generated by Django 5.2.15 on 2026-06-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
